myBlog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :posts
  resources :users do
    resources :posts do
      resources :comments
    end
  end
  resources :categories
end

myBlog/app/models/category.rb
class Category < ActiveRecord::Base
end

myBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: :post_id, dependent: :destroy
  has_many :replies, class_name:"Comment", foreign_key: :comment_id
end

myBlog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                      length: {minimum: 5}

end

myBlog/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
end

myBlog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts , foreign_key: :user_id, dependent: :destroy
  has_many :comments, foreign_key: :user_id, dependent: :destroy
end

myBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  # before_action :set_category, only: [:update, :show, :edit, :create ]

  # private
  # def set_category
  #   @categories = Category.all
  # end
end

myBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(params_category)
    if @category.save!
      flash[:notice] = "Category successfully created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(params_category)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def params_category
    params.require(:category).permit(:namecategory)
  end
end

myBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def create
     @post = Post.find_by(id: params[:post_id])
    if params[:submit] == "Comment"
      @post.comments.create(comment_params)
     flash[:notice] = "Comment successfully created"
    else
      @comment = Comment.find_by(id: params[:comment_id])
      @comment.replies.create(content: params[:content], user_id: current_user.id, post_id: @post.id)
      flash[:notice] = "Reply successfully created"
    end
    redirect_to user_post_path(user_id: current_user.id, id: @post.id)
  end

  private
    def comment_params
      params.permit(:content, :post_id, :user_id, :id)
    end
end

myBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :show, :edit, :destroy]

  def index
    # params[:user_id].present?
      @user = User.includes(:posts).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    @post.user_id = current_user.id if current_user
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
  end

  def edit
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :containt)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

myBlog/app/controllers/sessions_controller.rb
  class SessionsController < Devise::SessionsController
    def new
      get_pre_login_url
      super
    end

    def create
      @referer_url = root_path
      super
    end

    def destroy
      @referer_url = root_path
      super
    end

    private
    def get_pre_login_url
      @referer_url = root_path
    end

    def after_sign_in_path_for resource
      sign_in_url = url_for(action: "new", controller: "sessions", only_path: false, protocol: "http")
      if @referer_url == sign_in_url
        super
      else
        @referer_url || root_path
      end
    end
  end

myBlog/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_path, notice: 'Update Profile was successfully updated.'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :age)
  end

end

myBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<div class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.user_name || current_user.email %></strong>.
  <%= link_to 'Edit Password', edit_user_registration_path, :class => 'navbar-link' %>
  <%= link_to 'Edit Profile', edit_user_path(current_user.id), :class => 'navbar-link' %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</header>

<%= yield %>


</body>
</html>

myBlog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
          this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :containt %><br>
    <%= f.text_area :containt %>
  </p>
  <p>
    <%= f.submit %>
</p>
<%end%>

myBlog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>
<%= link_to 'Back', posts_path %>

myBlog/app/views/posts/index.html.erb
<h1>Listing My Post </h1>
<table>
  <tr>
    <th><strong>Title</strong></th>
    <th colspan="3"></th>
  </tr>
  <% current_user.posts.each do |post| %>
    <tr>
      <td><strong><%= post.title.capitalize %></strong></td>
      <td><%= link_to 'Show', user_post_path(current_user, post), action: "show" %></td>
      <td><%= link_to 'Edit', edit_user_post_path(current_user, post) %></td>
      <td><%= link_to 'Destroy', user_post_path(current_user, post),
                                                    method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New post', new_user_post_path(current_user) %><br>
<%= link_to 'New category', new_category_path %><br>

myBlog/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

myBlog/app/views/posts/show.html.erb
<main >
<div class="panel panel-primary" >
  <div class="panel-heading" >
    <strong>Title:</strong>
    <%= @post.title.capitalize %>
  </div>
  <div class="panel-body">
    <strong>CONTENT:</strong>
    <%= @post.containt %>
  </div >
</div>
</main>
<p>
  <% @post.comments.where(comment_id: nil).each do |comment| %>
    <strong>Comment:</strong>
    <%= comment.content %><br>
    <% comment.replies.each do |reply| %>
      <strong> >>> : </strong>
      <%= reply.content %><br>
    <%end%>
    <form action="/users/<%= current_user.id%>/posts/<%= @post.id %>/comments" method="post">
      <label>Reply</label><br>
      <textarea name="content">
      </textarea>
      <input type="hidden" name="comment_id" value="<%= comment.id %>">
      <input type="submit" name="submit" value="Reply" class="btn btn-success">
    </form>
  <%end%>
</p>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>

myBlog/app/views/users/edit.html.erb
<h1>Editing Profile</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', root_path %>

myBlog/app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>my Blog</title>
</head>
<body>
<p>Hello puu</p>
<%= link_to 'My Blog', controller: 'posts' %>
</body>
</html>