shoe_store/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  resources :categories
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  post   '/products/:id',   to: 'likes#create'

  resources :cookies
  resources :search

  resources :products, concerns: :paginatable do
    resources :comments
  end
  root 'products#index'

end

shoe_store/app/models/categories_products.rb
class CategoriesProducts < ActiveRecord::Base
end

shoe_store/app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
end

shoe_store/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :product, foreign_key: "product_id"
	belongs_to :user, foreign_key: "user_id"
	has_many :replies, class_name: "Comment", foreign_key: "comment_id"
end

shoe_store/app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :product, dependent: :destroy, foreign_key: "product_id"
	belongs_to :user, dependent: :destroy, foreign_key: "user_id"
end

shoe_store/app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :user, foreign_key: "user_id"
	has_many :comments , dependent: :destroy
	has_and_belongs_to_many :categories
	self.inheritance_column = nil
	before_create :set_default

  private
    def set_default
      self.views_count = 0
      self.likes_count = 0
    end
end

shoe_store/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :products, dependent: :destroy, foreign_key: "user_id"
  has_many :comments, dependent: :destroy, foreign_key: "user_id"
  mount_uploader :avatar, ImageUploader
  has_many :product_ordered, ->{order(UsersController.product_ordered_option).limit(15)}, class_name: "Product"
end

shoe_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_action :authenticate_user!
	before_action :sidebar
  def hello
    render html: "hello, world!"
  end

  def sidebar
  	@cate_sidebar = Category.all.includes(:products)
  end
end

shoe_store/app/controllers/categories_controller.rb
class CategoriesController<ApplicationController
	def show
		@category = Category.find(params[:id])
	end
end

shoe_store/app/controllers/category_product_controller.rb
class CategoryProductController<ApplicationController

end

shoe_store/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comment= Comment.all
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.save
		redirect_to product_path(params[:product_id])
	end

	private
	def comment_params
		params.require(:comment).permit(:user_id, :content, :product_id, :comment_id)
	end
end

shoe_store/app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
	@@thach=Hash.new
	def index
		cookies[:cart]=@@thach.to_s
	end
	def create
		@@thach[params[:product_id]]="#{params[:product_price]}"
		cookies[:cart]=@@thach.to_s
		redirect_to root_path
	end
	def destroy
		binding.pry
		@@thach[params[:product_id]]=nil
		redirect_to root_path
	end
end

shoe_store/app/controllers/likes_controller.rb
class LikesController < ActionController::Base
	def create
		if Like.where(product_id: params[:id],user_id: params[:user_id]).exists?
			redirect_to product_path(params[:id])
		else
			Like.create(product_id: params[:id],user_id: params[:user_id])
			redirect_to product_path(params[:id])
		end
	end
end

shoe_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		if params[:limit].nil?
			params[:limit]=10
		end
		@search = Product.ransack(params[:q])
		if params[:navigation].nil?
	    @products = @search.result.page(params[:page]).per(params[:limit])
	  elsif params[:navigation]=="new"
	  	@products = @search.result.page(params[:page]).per(params[:limit]).order(created_at: :desc)
	  else 
	    @products = @search.result.page(params[:page]).per(params[:limit]).order(views_count: :desc)
	  end
	end

	def new
		@product = Product.new
	end

	def show
		@product = Product.includes(:categories, comments: :replies).find(params[:id])
		@product.views_count+=1
		@product.save
	end

	def create
		@product = Product.new(product_params)
	  if @product.save
      if params[:product][:categories].present?
        params[:product][:categories].each do |cate|
        	CategoriesProducts.create(category_id: cate, product_id: @product.id)
        end
      end
      redirect_to root_path
    end
	end

	def destroy
		Product.destroy(params[:id])
		redirect_to root_path
	end

  private
  def product_params
    params.require(:product).permit(:image, :product_name, :price, :type, :user_id, :description)
  end
end

shoe_store/app/controllers/sessions_controller.rb
  class SessionsController < Devise::SessionsController
    def new
      get_pre_login_url
      super
    end
    def create
      @referer_url = products_path
      super
    end
    def destroy
      @referer_url = root_path
      super
    end
    private
    def get_pre_login_url
      @referer_url = root_path
    end
    def after_sign_in_path_for resource
      sign_in_url = url_for(action: "new", controller: "sessions", only_path: false, protocol: "http")
      if @referer_url == sign_in_url
      super
    else
      @referer_url || root_path
    end
    end
  end
  

shoe_store/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

shoe_store/app/controllers/users_controller.rb
class UsersController < ApplicationController
  class_attribute :product_ordered_option
  def edit
  end

  def index
    @users = User.all
  end
  def show
    # UsersController.product_ordered_option = params[:navigation]
    @user = User.find(params[:id])
    # @user.product_ordered
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user, notice: 'Update Profile was successfully updated.'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :telephone, :avatar)
  end
end

shoe_store/app/helpers/application_helper.rb
module ApplicationHelper

end

shoe_store/app/helpers/comments_helper.rb
module CommentsHelper
end

shoe_store/app/helpers/cookies_helper.rb
module CookiesHelper
end

shoe_store/app/helpers/users_helper.rb
module UsersHelper
end

shoe_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<header style="height: 80px">
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<!-- warning if not login -->
	<p class="navbar-text pull-right">
	<!-- navigation -->
	<% if user_signed_in? %>
		<div>
		  <ul>
		  	<li class="dropdown">
			    <a href="javascript:void(0)" class="dropbtn" onclick="DropdownMenu()"><%=current_user.email%></a>
			    <div class="dropdown-content" id="myDropdown">
			      <%= link_to "Profile", user_path(current_user.id)%>
			      <%= link_to "Update", edit_user_path(current_user.id)%>
			      <%= link_to "Reset pass", edit_user_registration_path%>
			    </div>
			  </li>
		  	<li><%= link_to "New", products_path(navigation: "new")%></li>
		  	<li><%= link_to "Hot", products_path(navigation: "hot")%></li>
		  	<li><%= link_to "Create post", new_product_path %></li>
		  	<li><%= link_to "Cart", cookies_path %></li>
		    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		    <li><%= link_to "Home", products_path %></li>  
		  </ul>
		</div>
		<br>
	<!-- search_box -->
	<br><br>
	<main>
		<nav class="w3-sidenav w3-white w3-card-2" style="width:18%; height: 400px;"><br>
		  <%@cate_sidebar.each do |cate|%>
	      <p><%= link_to "#{cate.content} (#{cate.products.length})", category_path(id: cate.id)%></p>
	    <%end%>
		</nav>
	</main>
	<br><br>
	<% else %>
		<div>
		  <ul>
		  	<li><%= link_to "Sign up", new_user_registration_path %></li>
		    <li><%= link_to "Login", new_user_session_path%></li>
		  </ul>
		</div>
		<br>
	<% end %>
</header>
<div style="margin-left: 20%">
	<%= yield %>
</div>


</body>
</html>