new_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'new#index'

  Rails.application.routes.draw do
    resources :new do 
      resources :comment
      resources :like
    end
  end

end

new_project/app/models/new.rb
class New < ActiveRecord::Base
	has_many :cats_news, foreign_key: :new_id
	has_many :comments, foreign_key: :new_id
	has_many :categories, through: :cats_news
	belongs_to :user
	has_many :likes, foreign_key: :new_id
end

new_project/app/controllers/new_controller.rb
class NewController < ApplicationController
	def index
		# binding.pry
		@news = New.all.page(params[:page]).per(6)
		# @news = New.all

		# @search = New.search(params[:q])
  #   		@news_search = @search.result



  		# @search = New.search(params[:q])
    # 		@news = @search.result
	end

	def new
		@cats = Category.all
	end	

	def create
		# binding.pry
		@new = New.new(name: params[:new][:name], description: params[:new][:description], content: params[:new][:content], user_id: current_user.id, vote: 0, picture: params[:new][:picture].original_filename)
		@new.save
		params[:new][:category].each do |cat|
			@cats_new = CatsNew.new(new_id: @new.id, cat_id: cat)
			@cats_new.save
		end

		redirect_to new_index_path
	end
	def edit
		binding.pry
		@cats = Category.all
		@new = New.find_by(id: params[:id])

	end
	def update
		binding.pry
		@new = New.find_by(id: params[:new][:id])

		redirect_to new_index_path
	end

	def show
		@new = New.find_by(id: params[:id])
		@new.vote += 1;
		@new.save
		# binding.pry
		@comments = @new.comments.where(comment_id: nil)
		# @comments = Comment.all
		# @comments = Comment.where(new_id: flash[:new_id])

	end

	def destroy
		New.destroy(params[:id])
		CatsNew.where(new_id: params[:id]).destroy_all
		redirect_to new_index_path
	end
end

new_project/app/views/new/edit.html.erb
	<h2 class="list_news">Edit new</h2>

	<section class="col-md-2"></section>
	<section class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">Edit new</div>
			<section class="panel-body">
				<%=form_for @new, url: {action: "update"} do |f|%>
					<section class="field">
						<%=f.label "Name: "%>
						<%=f.text_field :name, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Description"%>
						<%=f.text_field :description, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Content"%>
						<%=f.text_field :content, class: "form-control"%>
					</section>
					<%binding.pry%>
					<section class="field">
						<%=f.label "Category: "%>
						<%=f.select "category", @cats.collect{|cat| [cat.name, cat.id] }, {}, multiple: :multiple, size: 5, class: "form-control"%>
					</section>
					<section class="actions">
						<%=f.submit "Submit"%>
					</section>
				<%end%>
			</section>
		</div>		
	</section>

new_project/app/views/new/index.html.erb
<h2 class="list_news">List news</h2>
<div class="col-md-1"></div>
<%=button_to "Create new", new_new_path, method: :get, class: "btn btn-success create-new"%>

<section class="content">
	<!-- <section class="col-md-1"></section> -->
	
	<%@news.each do |item|%>
	<section class="col-md-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<%=item.name%>
			</div>
			<div class="panel-body">
				<%=item.description%>
			</div>
			<div class="function">
				<%=link_to "Show", new_path(item.id), method: :get%>
				<%=link_to "Edit", edit_new_path(item.id), method: :get%>
				<%=link_to "Del", new_path(item.id), method: :delete%>

			</div>
		</div>
	</section>
	<section class="col-md-1">
		
	</section>
	
	
	<%end%>
	<section>
		<%= paginate(@news)%>
	</section>
	
</section>

new_project/app/views/new/new.html.erb
	<h2 class="list_news">Create new</h2>

	<section class="col-md-2"></section>
	<section class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">Create new</div>
			<section class="panel-body">
				<%=form_for :new, url: {action: "create"} do |f|%>
					<section class="field">
						<%=f.label "Name: "%>
						<%=f.text_field :name, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Description"%>
						<%=f.text_field :description, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Content"%>
						<%=f.text_field :content, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Category: "%>
						<%=f.select "category", @cats.collect{|cat| [cat.name, cat.id] }, {}, multiple: :multiple, size: 5, class: "form-control"%>
					</section>
					<section class="field">
						<%=f.label "Picture: "%>
						<%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png, image/jpg"%>
					</section>
					<section class="actions">
						<%=f.submit "Submit", class: "btn btn-success"%>
					</section>
					
				<%end%>
			</section>
		</div>		
	</section>

new_project/app/views/new/show.html.erb
<h2 class="list_news">Show</h2>
<section class="col-md-2"></section>
	<section class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading name-new"><%=@new.name%></div>
			<section class="panel-body">
				<!-- <img src="cinqueterre.jpg" class="img-thumbnail" alt="Cinque Terre" width="304" height="236">  -->
				<%=image_tag  "#{@new.picture}"%>
				<section class="description"><%=@new.description%></section>
				<section class="content"><%=@new.content%></section>
				<section class="actions">
					<%=form_for :like, url: new_like_index_path(@new.id) do |f|%>
						<%=f.hidden_field current_user.id%>
						<%=f.submit "Like", class: "btn btn-primary btn-sm"%> <%=@new.like_count%>
					<%end%>
					<label></label>
				</section>
				<section class="comment">
					<p class="comment-section">Comments:</p>
					<form>
						<%@comments.each do |comment|%>
							<section class="comment-main">
								<label class="comment-user">User <%=comment.user_id%>:</label>
								<label class="comment-content"><%=comment.content%></label>
								<%if current_user.id == comment.user_id %>
									<%=link_to "Del", new_comment_path(new_id: @new.id, id: comment.id), method: :delete%>
								<%end%>
							</section>
							<%comment.reply.each do |reply|%>
								<section class="reply-main">
									<label class="reply-user">User <%=reply.user_id%>:</label>
									<label class="reply-content"><%=reply.content%></label>
								</section>
							<%end%>
							<section class="reply-form">
								<!-- <input type="text" name="reply"  class="form-control reply-main reply-input">
								<input type="hidden" name="comment_id" value="<%=comment.id%>">
								<input type="submit" name="submit" value="reply" class="btn btn-success comment reply-main"> -->
								<%=form_for :comment, url: new_comment_index_path(@new.id)  do |f|%>
										<%=f.text_field :content, class: "form-control reply-main reply-input"%>
										<%=f.hidden_field :comment_id%>
										<%=f.submit "Reply", class: "btn btn-success comment reply-main"%>
								<%end%>
							</section>
							
						<%end%>
					</form>
					
					
				</section>
				<%=form_for :comment, url: new_comment_index_path(@new.id) do |f|%>
				<%flash[:new_id] = @new.id%>
					<%=f.text_field :content, class: "form-control comment comment-input"%>
					<%=f.submit "Comment", class: "btn btn-success comment"%>
				<%end%>
			</section>
		</div>		